#ifndef LIB_SYNTH_DEFS_H
#define LIB_SYNTH_DEFS_H

#define PANEL_ATTACHED

#define CC_ARGS_MAX_LENGTH 8
#define LFO_NUM_VALUES 256
#define LFO_MAX_FREQ 20

#define NUM_CHANNELS	3
#define NUM_CV			5
#define MAX_CC 128
#define NUM_LFO			2

#define WAVES_PATH "waves/"
#define PRESETS_PATH "presets/"

enum {
	SUB0 = 0x01,
	SUB1 = 0x02,
	SUB2 = 0x04,
	NOISE_EN = 0x08	
};

//lfo targets
enum {
	LFO_TARGET_NONE,
	LFO_TARGET_PITCH,
	LFO_TARGET_CV,
	LFO_TARGET_RATE,
	LFO_TARGET_DEPTH
};

//CV numbers
enum {
	CUTOFF = 0x00,
	RESONANCE = 0x01,
	AMP = 0x02,
	NOISE = 0x03,
	SUB = 0x04
};

//ADSR params
enum {
	ATTACK = 0,
	DECAY = 2,
	RELEASE = 4,
	SUSTAIN = 6,
	CUTOFF_MIX = 7,
	AMP_MIX = 8
};

typedef enum ccType_t{
	LFO_RATE = 0x00,
	LFO_DEPTH = 0x01,
	CV = 0x03,
	WT_WAVE = 0x04,
	WT_TUNE = 0x05,
	WT_TRANSPOSE = 0x06,
	WT_VOLUME = 0x07,
	WT_SUB = 0x08,
	PARA_MODE = 0x09,
	GLIDE_TIME = 0x0A,
	ENV = 0x0B,
	LFO_WAVE = 0x0C,
	CC_TYPE_LFO_TARGET = 0x0D,
	PRESET_LOAD_SELECT,
	PRESET_LOAD_ENTER,
	PRESET_STORE_SELECT,
	PRESET_STORE_ENTER
};

#define CC_WT_WAVE 26
#define CC_WT_TRANSPOSE 6
#define CC_WT_TUNE 2
#define CC_WT_VOLUME 27
#define CC_GLIDE_TIME 9
#define CC_CUTOFF 74
#define CC_RESONANCE 71
#define CC_ATTACK 73
#define CC_DECAY 15
#define CC_SUSTAIN 16
#define CC_RELEASE 72
#define CC_ENV_CUTOFF_MIX 10
#define CC_ENV_AMP_MIX 11
#define CC_AMP 7
#define CC_SUB 13
#define CC_NOISE 20
#define CC_LFO_TARGET 21
#define CC_LFO_RATE 22
#define CC_LFO_DEPTH 23
#define CC_LFO_WAVE 29
#define CC_PRESET_LOAD_SELECT 124
#define CC_PRESET_LOAD_ENTER 125
#define CC_PRESET_STORE_SELECT 126
#define CC_PRESET_STORE_ENTER 127
#define CC_PARA_MODE 25

#endif